networks:
  grafana:

volumes:
  grafana-storage:
    name: grafana 
  prometheus-storage:
    name: prometheus
  loki-s3:
    name: loki

services:
  loki-backend:
    container_name: loki_backend
    image: grafana/loki
    platform: linux/arm64
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    depends_on:
      - loki-proxy
    healthcheck:
      test: [  "CMD", "loki", "-health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana


  loki-read:
    container_name: loki_read
    image: grafana/loki
    platform: linux/arm64
    command: "-config.file=/etc/loki/config.yaml -target=read"
    ports:
      - 3101:3100
      - "7946"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: [  "CMD", "loki", "-health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: &loki-dns
      grafana:
        aliases:
          - loki


  loki-write:
    container_name: loki_write
    image: grafana/loki
    platform: linux/arm64
    command: "-config.file=/etc/loki/config.yaml -target=write"
    ports:
      - 3102:3100
      - "7946"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    healthcheck:
      test: [ "CMD", "loki", "-health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio
    networks:
      <<: *loki-dns

  loki-proxy:
    container_name: loki_proxy
    image: nginx
    platform: linux/arm64
    depends_on:
      - loki-read
      - loki-write
    volumes:
      - ./loki-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana

  # Might be moving this to garage (https://github.com/deuxfleurs-org/garage) as minio community support is ending .
  # have already tested garage and believe it would be a good replacement for this.
  minio:
    container_name: minio_s3
    image: minio/minio
    platform: linux/arm64
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9000"
    volumes:
      - loki-s3:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - grafana


  grafana:
    container_name: grafana
    image: grafana/grafana
    platform: linux/arm64
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - TENANT_ID=${TENANT_ID}
    depends_on:
      - loki-proxy
      - prometheus
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/ds.yaml
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana


  prometheus:
    container_name: prometheus
    image: prom/prometheus
    platform: linux/arm64
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    healthcheck:
      test: [ "CMD-SHELL", "/bin/wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana
