services:
  # Collector for Loki and Prometheus
  alloy:
    image: grafana/alloy:latest
    platform: linux/arm64
    volumes:
      - ./alloy.conf:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:  run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - 12345:12345
