services:
  # Collector for Loki and Prometheus
  alloy:
    container_name: alloy
    image: grafana/alloy
    platform: linux/arm64
    privileged: true
    mem_limit: 400m
    environment:
      - PROM_ENDPOINT=http://${NODE_NAME}:9090/api/v1/write
      - LOKI_ENDPOINT=http://${NODE_NAME}:3100/loki/api/v1/push
      - NODE_NAME=${NODE_NAME}
      - TENANT_ID=${TENANT_ID}
    ports:
      - 12345:12345
    volumes:
      - ./alloy.conf:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /:/rootfs:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
